"""Script generator: convert RecordedEvent list to a Python test script string."""
from __future__ import annotations

from omniui.core.models import RecordedEvent
from .selector_inference import infer_selector

_HEADER = """\
# Generated by OmniUI Recorder
from omniui import OmniUI

client = OmniUI.connect()
"""


def _selector_kwargs(sel: dict) -> str:
    fragile = sel.pop("_fragile", False)
    parts = ", ".join(f'{k}="{v}"' if isinstance(v, str) else f"{k}={v}" for k, v in sel.items())
    suffix = "  # WARN: fragile selector" if fragile else ""
    return parts, suffix


def generate_script(events: list[RecordedEvent]) -> str:
    """Return a Python script string for the given *events*."""
    lines = [_HEADER]
    for event in events:
        sel = infer_selector(event)
        kwargs, suffix = _selector_kwargs(sel)
        if event.event_type == "click":
            lines.append(f'client.click({kwargs}){suffix}')
        elif event.event_type == "type":
            lines.append(f'client.type({kwargs}, text="{event.text}"){suffix}')
    return "\n".join(lines) + "\n"
