"""Script generator: convert RecordedEvent list to a Python test script string."""
from __future__ import annotations

from omniui.core.models import RecordedEvent
from .selector_inference import infer_selector
from .wait_injection import inject_waits

_HEADER = """\
# Generated by OmniUI Recorder
from omniui import OmniUI

client = OmniUI.connect()
"""


def _selector_kwargs(sel: dict) -> str:
    fragile = sel.pop("_fragile", False)
    parts = ", ".join(f'{k}="{v}"' if isinstance(v, str) else f"{k}={v}" for k, v in sel.items())
    suffix = "  # WARN: fragile selector" if fragile else ""
    return parts, suffix


def _drag_line(event: "RecordedEvent") -> str:
    """Return a drag().to() line for a drag event."""
    from_sel = infer_selector(event)
    from_kwargs, from_suffix = _selector_kwargs(from_sel)

    # Build a synthetic "to" event using to_* fields
    from omniui.core.models import RecordedEvent as RE
    to_event = RE(
        event_type="drag_to",
        fx_id=event.to_fx_id,
        text=event.to_text,
        node_type=event.to_node_type,
        node_index=event.to_node_index,
        timestamp=event.timestamp,
    )
    to_sel = infer_selector(to_event)
    to_kwargs, to_suffix = _selector_kwargs(to_sel)
    suffix = from_suffix or to_suffix
    return f"client.drag({from_kwargs}).to({to_kwargs}){suffix}"


def generate_script(
    events: list[RecordedEvent],
    wait_injection: bool = False,
    wait_timeout: float = 5.0,
) -> str:
    """Return a Python script string for the given *events*.

    Args:
        events: Recorded events from the Java agent.
        wait_injection: If ``True``, insert ``wait_for_enabled`` /
            ``wait_for_visible`` lines before each action so that the
            replayed script waits for the UI to be ready instead of
            relying on fixed ``time.sleep`` calls.
        wait_timeout: Timeout (seconds) passed to each injected wait call.
    """
    action_lines: list[str] = []
    action_events: list[RecordedEvent] = []

    for event in events:
        sel = infer_selector(event)
        kwargs, suffix = _selector_kwargs(sel)
        if event.event_type == "click":
            action_lines.append(f'client.click({kwargs}){suffix}')
            action_events.append(event)
        elif event.event_type == "type":
            action_lines.append(f'client.type({kwargs}, text="{event.text}"){suffix}')
            action_events.append(event)
        elif event.event_type == "drag":
            action_lines.append(_drag_line(event))
            action_events.append(event)
        elif event.event_type == "set_color":
            color_val = event.color or "#000000"
            if event.fx_id:
                action_lines.append(f'client.set_color("{color_val}", id="{event.fx_id}")')
            else:
                action_lines.append(f'client.set_color("{color_val}")')
            action_events.append(event)
        elif event.event_type == "select_combo":
            value_str = event.text or ""
            if event.fx_id:
                action_lines.append(f'client.select("{value_str}", id="{event.fx_id}")')
            else:
                action_lines.append(f'client.select("{value_str}")')
            action_events.append(event)
        elif event.event_type == "set_date":
            date_val = event.text or ""
            if event.fx_id:
                action_lines.append(f'client.set_date("{date_val}", id="{event.fx_id}")')
            else:
                action_lines.append(f'client.set_date("{date_val}")')
            action_events.append(event)
        elif event.event_type == "dismiss_dialog":
            button_text = event.text or "OK"
            action_lines.append(f'client.dismiss_dialog(button="{button_text}")')
            action_events.append(event)

    if wait_injection:
        body_lines = inject_waits(action_events, action_lines, timeout=wait_timeout)
    else:
        body_lines = action_lines

    lines = [_HEADER] + body_lines
    return "\n".join(lines) + "\n"

