"""Script generator: convert RecordedEvent list to a Python test script string."""
from __future__ import annotations

from omniui.core.models import RecordedEvent
from .selector_inference import infer_selector
from .wait_injection import inject_waits

_HEADER = """\
# Generated by OmniUI Recorder
from omniui import OmniUI

client = OmniUI.connect()
"""


def _selector_kwargs(sel: dict) -> str:
    fragile = sel.pop("_fragile", False)
    parts = ", ".join(f'{k}="{v}"' if isinstance(v, str) else f"{k}={v}" for k, v in sel.items())
    suffix = "  # WARN: fragile selector" if fragile else ""
    return parts, suffix


def generate_script(
    events: list[RecordedEvent],
    wait_injection: bool = False,
    wait_timeout: float = 5.0,
) -> str:
    """Return a Python script string for the given *events*.

    Args:
        events: Recorded events from the Java agent.
        wait_injection: If ``True``, insert ``wait_for_enabled`` /
            ``wait_for_visible`` lines before each action so that the
            replayed script waits for the UI to be ready instead of
            relying on fixed ``time.sleep`` calls.
        wait_timeout: Timeout (seconds) passed to each injected wait call.
    """
    action_lines: list[str] = []
    action_events: list[RecordedEvent] = []

    for event in events:
        sel = infer_selector(event)
        kwargs, suffix = _selector_kwargs(sel)
        if event.event_type == "click":
            action_lines.append(f'client.click({kwargs}){suffix}')
            action_events.append(event)
        elif event.event_type == "type":
            action_lines.append(f'client.type({kwargs}, text="{event.text}"){suffix}')
            action_events.append(event)

    if wait_injection:
        body_lines = inject_waits(action_events, action_lines, timeout=wait_timeout)
    else:
        body_lines = action_lines

    lines = [_HEADER] + body_lines
    return "\n".join(lines) + "\n"

